[package]
name = "csim"
version = "0.1.0"
authors = ["Sameer Ismail <38896593+sentalis@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
